alter table KVARTPLATOMER_BILL add constraint FK_KVARTPLATOMER_BILL_ON_OBJECT foreign key (OBJECT_ID) references KVARTPLATOMER_OBJECT(ID);
alter table KVARTPLATOMER_BILL add constraint FK_KVARTPLATOMER_BILL_ON_SERVICE_ACCOUNT foreign key (SERVICE_ACCOUNT_ID) references KVARTPLATOMER_SERVICE_ACCOUNT(ID);
create index IDX_KVARTPLATOMER_BILL_ON_OBJECT on KVARTPLATOMER_BILL (OBJECT_ID);
create index IDX_KVARTPLATOMER_BILL_ON_SERVICE_ACCOUNT on KVARTPLATOMER_BILL (SERVICE_ACCOUNT_ID);
